version: "3.9"

services:
  app:
    # ==============================
    # Build từ thư mục server
    # ==============================
    build:
      context: ./server
      dockerfile: Dockerfile

    container_name: ie213_backend

    # ==============================
    # Map port máy thật → container
    # ==============================
    ports:
      - "5000:5000"

    # ==============================
    # Load biến môi trường
    # ==============================
    env_file:
      - ./server/.env

    # ==============================
    # Mount code (dev mode)
    # sửa code không cần rebuild
    # ==============================
    volumes:
      - ./server:/app
      - /app/node_modules

    # ==============================
    # Tự restart nếu crash
    # ==============================
    restart: always
